users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /user

app_job:
    resource: "@AppBundle/Resources/config/routing/job.yml"
    prefix:   /

app_category:
    resource: "@AppBundle/Resources/config/routing/category.yml"
    prefix:   /category

app_categoryaffiliate:
    resource: "@AppBundle/Resources/config/routing/categoryaffiliate.yml"
    prefix:   /categoryaffiliate

app_affiliate:
    resource: "@AppBundle/Resources/config/routing/affiliate.yml"
    prefix:   /affiliate

# app/config/routing.yml

