affiliate_index:
    path:     /
    defaults: { _controller: "AppBundle:Affiliate:index" }
    methods:  GET

affiliate_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Affiliate:show" }
    methods:  GET

affiliate_new:
    path:     /new
    defaults: { _controller: "AppBundle:Affiliate:new" }
    methods:  [GET, POST]

affiliate_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Affiliate:edit" }
    methods:  [GET, POST]

affiliate_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Affiliate:delete" }
    methods:  DELETE
