categoryaffiliate_index:
    path:     /
    defaults: { _controller: "AppBundle:Categoryaffiliate:index" }
    methods:  GET

categoryaffiliate_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Categoryaffiliate:show" }
    methods:  GET

categoryaffiliate_new:
    path:     /new
    defaults: { _controller: "AppBundle:Categoryaffiliate:new" }
    methods:  [GET, POST]

categoryaffiliate_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Categoryaffiliate:edit" }
    methods:  [GET, POST]

categoryaffiliate_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Categoryaffiliate:delete" }
    methods:  DELETE
