job_index:
    path:     /admin
    defaults: { _controller: "AppBundle:Job:index" }
    methods:  GET

job_userindex:
    path:     /
    defaults: { _controller: "AppBundle:Job:index1" }
    methods:  GET|POST

job_description:
    path:     /description
    defaults: { _controller: "AppBundle:Job:jobdescription" }
    methods:  GET|POST

job_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Job:show" }
    methods:  GET

job_new:
    path:     /new
    defaults: { _controller: "AppBundle:Job:new" }
    methods:  [GET, POST]

job_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Job:edit" }
    methods:  [GET, POST]

job_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Job:delete" }
    methods:  DELETE


