AppBundle\Entity\Affiliate:
    type: entity
    table: affiliate
    uniqueConstraints:
        email:
            columns:
                - email
    id:
        idAffiliate:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_affiliate
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        token:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        isActive:
            type: boolean
            nullable: true
            column: is_active
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    lifecycleCallbacks: {  }
